export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import AuthButton from "../app/components/AuthButton";

export default function Home() {
  return (
    <div>
      <AuthButton />
    </div>
  );
}
